language: c
sudo: false # only for faster builds
compiler:
 - gcc
script:
 - gcc -o file1 file1.c // we can use gcc instead of clang too
 - ./file1
 - gcc -o file2 file2.c // we can use gcc instead of clang too
 - ./file1
